/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./*.js",
    "./src/**/*.{js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        'slate': {
          900: '#0f172a',
          800: '#1e293b',
          700: '#334155',
          600: '#475569',
          500: '#64748b',
          400: '#94a3b8',
          300: '#cbd5e1',
          200: '#e2e8f0',
          100: '#f1f5f9',
          50: '#f8fafc',
        },
        'orange': {
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        }
      },
      animation: {
        'pulse-green': 'pulse-green 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
        'slide-in-up': 'slide-in-up 0.6s ease-out',
      },
      keyframes: {
        'pulse-green': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.5' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        'slide-in-up': {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        }
      }
    },
  },
  plugins: [],
  // Only include the utilities we actually use
  safelist: [
    'bg-slate-900',
    'text-slate-300',
    'text-white',
    'text-orange-500',
    'text-green-400',
    'text-green-300',
    'text-slate-400',
    'bg-orange-600',
    'bg-orange-500',
    'bg-white',
    'bg-gray-900',
    'bg-gray-800',
    'bg-blue-600',
    'bg-green-600',
    'bg-purple-600',
    'bg-red-600',
    'border-gray-700',
    'border-orange-500',
    'border-white',
    'rounded-full',
    'rounded-2xl',
    'rounded-lg',
    'px-6',
    'px-8',
    'px-4',
    'py-4',
    'py-3',
    'py-2',
    'py-24',
    'py-8',
    'py-6',
    'mb-8',
    'mb-12',
    'mt-4',
    'mt-6',
    'pt-6',
    'pt-8',
    'space-x-3',
    'space-x-4',
    'space-x-8',
    'space-y-3',
    'space-y-4',
    'space-y-8',
    'gap-4',
    'gap-8',
    'w-full',
    'w-6',
    'w-5',
    'w-4',
    'w-3',
    'w-2',
    'w-1',
    'h-6',
    'h-5',
    'h-4',
    'h-3',
    'h-2',
    'h-1',
    'text-2xl',
    'text-lg',
    'text-sm',
    'text-xs',
    'font-bold',
    'font-semibold',
    'font-medium',
    'hidden',
    'block',
    'flex',
    'inline-flex',
    'grid',
    'items-center',
    'justify-center',
    'justify-between',
    'text-center',
    'relative',
    'absolute',
    'sticky',
    'top-0',
    'top-10',
    'right-10',
    'z-50',
    'overflow-hidden',
    'container',
    'mx-auto',
    'transform',
    'transition-all',
    'duration-300',
    'duration-1000',
    'hover:bg-orange-500',
    'hover:from-orange-500',
    'hover:to-orange-400',
    'hover:bg-orange-500/10',
    'hover:border-orange-500',
    'hover:transform',
    'hover:-translate-y-1',
    'hover:-translate-y-2',
    'hover:shadow-xl',
    'hover:shadow-2xl',
    'hover:text-orange-400',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-orange-500',
    'focus:ring-offset-2',
    'focus:ring-offset-gray-900',
    'group',
    'group-hover:text-orange-400',
    'lg:block',
    'md:flex',
    'sm:flex-row',
    'sm:flex-col',
    'xl:grid-cols-4',
    'xl:grid-cols-3',
    'xl:grid-cols-2',
    'xl:gap-8',
    'xl:px-8',
    'xl:py-12',
    'xl:text-4xl',
    'xl:text-3xl',
    'xl:text-2xl',
    'xl:text-xl',
    'xl:text-lg',
    'xl:text-base',
    'xl:text-sm',
    'xl:text-xs',
    'xl:font-bold',
    'xl:font-semibold',
    'xl:font-medium',
    'xl:font-normal',
    'xl:font-light',
    'xl:font-thin',
    'xl:font-extrabold',
    'xl:font-black',
    'xl:bg-slate-900',
    'xl:bg-gray-900',
    'xl:bg-white',
    'xl:bg-orange-600',
    'xl:bg-orange-500',
    'xl:bg-blue-600',
    'xl:bg-green-600',
    'xl:bg-purple-600',
    'xl:bg-red-600',
    'xl:text-white',
    'xl:text-slate-300',
    'xl:text-orange-500',
    'xl:text-green-400',
    'xl:text-green-300',
    'xl:text-slate-400',
    'xl:border-gray-700',
    'xl:border-orange-500',
    'xl:border-white',
    'xl:rounded-full',
    'xl:rounded-2xl',
    'xl:rounded-lg',
    'xl:px-6',
    'xl:px-8',
    'xl:px-4',
    'xl:py-4',
    'xl:py-3',
    'xl:py-2',
    'xl:py-24',
    'xl:py-8',
    'xl:py-6',
    'xl:mb-8',
    'xl:mb-12',
    'xl:mt-4',
    'xl:mt-6',
    'xl:pt-6',
    'xl:pt-8',
    'xl:space-x-3',
    'xl:space-x-4',
    'xl:space-x-8',
    'xl:space-y-3',
    'xl:space-y-4',
    'xl:space-y-8',
    'xl:gap-4',
    'xl:gap-8',
    'xl:w-full',
    'xl:w-6',
    'xl:w-5',
    'xl:w-4',
    'xl:w-3',
    'xl:w-2',
    'xl:w-1',
    'xl:h-6',
    'xl:h-5',
    'xl:h-4',
    'xl:h-3',
    'xl:h-2',
    'xl:h-1',
    'xl:text-2xl',
    'xl:text-lg',
    'xl:text-sm',
    'xl:text-xs',
    'xl:font-bold',
    'xl:font-semibold',
    'xl:font-medium',
    'xl:font-normal',
    'xl:font-light',
    'xl:font-thin',
    'xl:font-extrabold',
    'xl:font-black',
    'xl:hidden',
    'xl:block',
    'xl:flex',
    'xl:inline-flex',
    'xl:grid',
    'xl:items-center',
    'xl:justify-center',
    'xl:justify-between',
    'xl:text-center',
    'xl:relative',
    'xl:absolute',
    'xl:sticky',
    'xl:top-0',
    'xl:top-10',
    'xl:right-10',
    'xl:z-50',
    'xl:overflow-hidden',
    'xl:container',
    'xl:mx-auto',
    'xl:transform',
    'xl:transition-all',
    'xl:duration-300',
    'xl:duration-1000',
    'xl:hover:bg-orange-500',
    'xl:hover:from-orange-500',
    'xl:hover:to-orange-400',
    'xl:hover:bg-orange-500/10',
    'xl:hover:border-orange-500',
    'xl:hover:transform',
    'xl:hover:-translate-y-1',
    'xl:hover:-translate-y-2',
    'xl:hover:shadow-xl',
    'xl:hover:shadow-2xl',
    'xl:hover:text-orange-400',
    'xl:focus:outline-none',
    'xl:focus:ring-2',
    'xl:focus:ring-orange-500',
    'xl:focus:ring-offset-2',
    'xl:focus:ring-offset-gray-900',
    'xl:group',
    'xl:group-hover:text-orange-400'
  ]
}
